### ISSUE TITLE
关于无缝播放，闪动问题？

### ISSUE THREAD

**Issue by eekidu** [Doikki/DKVideoPlayer#493]
你好，通过removeView addView，共享一个播放器，实现无缝播放，遇到addView后，播放器闪动的问题。我看Demo中，退回到列表，播放器还回列表时，好像也有一个闪动。是不是surfaceView 引起的的，请指教？

**Comment by dueeeke** [comment]
目前我这种实现方式无解，并不是你说的surfaceView 引起的
