### ISSUE TITLE
屏幕常亮问题？

### ISSUE THREAD

**Issue by eekidu** [Doikki/DKVideoPlayer#500]
start() 方法中的` mPlayerContainer.setKeepScreenOn(true);`
这个设置在有些场景时会失效。可能跟播放器还没有attachToWindow有关。
Demo中无缝切换，不是无缝播放的情况下就会失效。

视频播放时，屏幕是否常亮，有时候是要求不能常亮，而是随着页面熄灭而暂停视频。希望这块设计的时候，可以考虑一下这个场景。

**Comment by dueeeke** [comment]
不会考虑这场景
