### ISSUE TITLE
关于抖音列表下网络请求视频方面代码

### ISSUE THREAD

**Issue by 1396748809** [Doikki/DKVideoPlayer#501]
我目前使用的是VerticalViewPager

**Comment by 1396748809** [comment]
> 
> 
> 我目前使用的是VerticalViewPager
TikTok2Activity中已经加载到网络请求的实体Bean，startPlay（）实在没看懂，addData（）放法我把参数替换成我加载出来的bean但是还是显示不出来，打log发现没有走startplay中的for方法！求大神帮帮忙！

**Comment by dueeeke** [comment]
多看几遍

**Comment by 1396748809** [comment]
好的，已经有进展了！感谢！



---原始邮件---
发件人: "dueeeke"<notifications@github.com&gt;
发送时间: 2020年4月27日(周一) 上午10:17
收件人: "dueeeke/DKVideoPlayer"<DKVideoPlayer@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"1396748809"<1396748809@qq.com&gt;;
主题: Re: [dueeeke/DKVideoPlayer] 关于抖音列表下网络请求视频方面代码 (#501)




 
多看几遍
