### ISSUE TITLE
Android P 使用 videocache:3.2.6 缓存问题

### ISSUE THREAD

**Issue by DeathLove4** [Doikki/DKVideoPlayer#505]
开发者你好，我的项目需要缓存功能，所以使用了 videocache：3.2.6。但是在Android P及以上设备上通过
 HttpProxyCacheServer cacheServer = ProxyVideoCacheManager.getProxy(this);
 String proxyUrl = cacheServer.getProxyUrl(SAMPLE_URL);
 mVideoView.setUrl(proxyUrl);
视频是无法缓存和播放的，在项目中配置了
 android:networkSecurityConfig  之后是可以的。
这个原因应该是 在AndroidVideoCache中使用了一个缓存代理地址：http://127.0.0.1，
所以会出问题，但是我看你的Sample中没有配置android:networkSecurityConfig，然而你的Sample在Android P上又是可以使用缓存功能，所以特想请教下你是怎么操作的！

**Comment by Doikki** [comment]
android:usesCleartextTraffic="true"

**Comment by DeathLove4** [comment]
好吧，非常感谢！
