### ISSUE TITLE
IAndroidIO 不起效

### ISSUE THREAD

**Issue by onexuan** [Doikki/DKVideoPlayer#509]
增加callback IAndroidIO时，没有回调

**Comment by Doikki** [comment]
啥意思

**Comment by onexuan** [comment]
ijkplayer有个接口 IjkMediaPlayer.java
public void setAndroidIOCallback(IAndroidIO androidIO)
            throws IllegalArgumentException, SecurityException, IllegalStateException {
        _setAndroidIOCallback(androidIO);
    }
没有回调

**Comment by Doikki** [comment]
你要用这个接口来做什么

**Comment by onexuan** [comment]
好像可以监听网络下载byte[]

**Comment by onexuan** [comment]
再反馈一下问题，videocache在华为10应该不行了，socket起不来了

**Comment by Doikki** [comment]
这个接口并不是用开监听io的

**Comment by Doikki** [comment]
加上这个`android:usesCleartextTraffic="true"`能起的来吗

**Comment by onexuan** [comment]
https://github.com/bilibili/ijkplayer/issues/3562 我是看到这个，所以认为它可能获取网络流

android:usesCleartextTraffic="true" 有加

**Comment by Doikki** [comment]
#3924 #3866 你理解错了

**Comment by Doikki** [comment]
华为Android 10不能socket起不来有什么日志输出吗，我手上没有华为手机

**Comment by onexuan** [comment]
> [bilibili/ijkplayer#3924](https://github.com/bilibili/ijkplayer/issues/3924) [bilibili/ijkplayer#3866](https://github.com/bilibili/ijkplayer/issues/3866) 你理解错了

那ijkplayer 同样定义了一个IMediaDataSource接口，也是同样的

**Comment by onexuan** [comment]
> 华为Android 10不能socket起不来有什么日志输出吗，我手上没有华为手机

不是日志，是无法用videocache代理HTTP缓存

**Comment by Doikki** [comment]
我找了一部Android10 的华为手机测试是正常的啊

**Comment by onexuan** [comment]
得找到mate 20看看，打开Logger 的日志
VideoCache: Closing socket… Socket is closed by client.
VideoCache: HttpProxyCacheServer error
VideoCache: Failed to close socket on proxy side: {}. It seems client have already closed connection.

而且运行demo 时被华为列为病毒，看看什么原因

**Comment by pengjunhong** [comment]
@Doikki 华为调试的话 可以去华为开发者平台那边 有云真机测试

**Comment by Doikki** [comment]
@pengjunhong 华为开发平台没有Android 10的mate20

**Comment by yangdengxueshi** [comment]
> 病毒

Demo华为报病毒  注释掉所有 signingConfig 可解决

**Comment by onexuan** [comment]
@yangdengxueshi 赞
