### ISSUE TITLE
华为手机被提示病毒风险了，能否说下是啥原因导致的，这块以后自己开发也可以避免。

### ISSUE THREAD

**Issue by pengjunhong** [Doikki/DKVideoPlayer#516]
下了几个高start的 ，其他都挺正常的。

![1](https://user-images.githubusercontent.com/18617995/81395057-8c480800-9155-11ea-844b-c6864250fdec.jpg)

**Comment by Doikki** [comment]
属于误报，可能是我MainActivity用了反射

**Comment by pengjunhong** [comment]
嗯 刚刚实验了 发现问题是您在gradle.properties中存入key 得密钥，去掉就可以了

**Comment by LannyLee** [comment]
@pengjunhong  为什么我签名的别名和密码 放入build.gradle 中了 依然提示病毒，并未向您所说的那样可以了

**Comment by yangdengxueshi** [comment]
Demo华为报病毒  注释掉所有 signingConfig 可解决
