### ISSUE TITLE
SeamlessPlayFragment跳转到详情页再回来会闪烁一下如何解决

### ISSUE THREAD

**Issue by Liberations** [Doikki/DKVideoPlayer#518]
RT

**Comment by Doikki** [comment]
无解

**Comment by WU1208** [comment]
有人解决了么？解决的希望回答下

**Comment by WU1208** [comment]
> 有人解决了么？解决的希望回答下

主要是动画问题，也就是共享元素动画，去掉动画后，没有出现问题。所以，要么更换动画效果，或者可以参考https://github.com/zzh12138/JZVideoDemo，使用Fragment完成动画。具体迁移我还没试过，什么时候有空再弄下
