### ISSUE TITLE
顶部状态信息怎么去掉呢？

### ISSUE THREAD

**Issue by yueye410** [Doikki/DKVideoPlayer#528]
![image](https://user-images.githubusercontent.com/9267858/82141565-5b5c8700-9869-11ea-9e36-0f98977beb5d.png)
这里的状态信息怎么去掉呢？
谢谢。

**Comment by yueye410** [comment]
[http://ktvimgs.lxpeng.net/B8890A41-5025-4D53-B7FC-D3CF3A3FC219.png](url)

**Comment by LannyLee** [comment]
@yueye410  这个是作者自定义的，你可以随意控制，具体到作者demo中的代码是，PlayerActivity。java中的 ` controller.addControlComponent(new DebugInfoView(this));`

**Comment by yueye410** [comment]
> @yueye410 这个是作者自定义的，你可以随意控制，具体到作者demo中的代码是，PlayerActivity。java中的 ` controller.addControlComponent(new DebugInfoView(this));`

好的，看到了，谢谢。
