### ISSUE TITLE
使用无缝播放的问题

### ISSUE THREAD

**Issue by supercwn** [Doikki/DKVideoPlayer#533]
很感谢有这么好用的库，但是在使用的时候遇到个小问题。在列表播放的时候，跳转到详情界面进行无缝播放，此时需要停止列表的播放，怎么实现呢

**Comment by supercwn** [comment]
类似头条里面的播放的功能

**Comment by Greathfs** [comment]
共用一个播放器就行了 一个播放器对应多个SurfaceView 类似一个主机对应多个显示器
