### ISSUE TITLE
进度条拖动ANR

### ISSUE THREAD

**Issue by DeathLove4** [Doikki/DKVideoPlayer#535]
开发者你好，我在使用你的播放器框架的时候，发现拖动进度条会出现ANR，过一会儿又自动播放了。。。
![Uploading image.png…]()
求助一下，有没有什么解决方案。。。
测试手机：华为P9 plus，Android 版本 8.0.0

**Comment by DeathLove4** [comment]
2020-05-29 15:33:47.448 18830-18973/com.app.debug E/CrashReport: # CRASH STACK: 
2020-05-29 15:33:47.448 18830-18973/com.app.debug E/CrashReport: android.media.MediaPlayer.getPlaybackParams(Native Method)
    com.dueeeke.videoplayer.player.AndroidMediaPlayer.getSpeed(AndroidMediaPlayer.java:202)
    com.dueeeke.videoplayer.player.VideoView.getSpeed(VideoView.java:607)
    com.dueeeke.videoplayer.controller.ControlWrapper.getSpeed(ControlWrapper.java:95)
    com.dueeeke.videoplayer.controller.BaseVideoController$2.run(BaseVideoController.java:312)

**Comment by wywangyunying** [comment]
同问，我使用了demo里的仿抖音播放视频，拖动视频的进度条时，经常会发生ANR
2020-06-03 10:24:51.072 1293-1309/? E/ActivityManager: ANR in com.hanweb.cx.activity (com.hanweb.cx.activity/.module.activity.VideoActivity)
    PID: 20686
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 50.  Wait queue head age: 5503.3ms.)
    Load: 5.79 / 5.51 / 5.2
    cpu0{ online=1 scaling_cur_freq=1958400 cpuinfo_max_freq=1958400 cpuinfo_min_freq=960000 }
    cpu1{ online=1 scaling_cur_freq=1958400 cpuinfo_max_freq=1958400 cpuinfo_min_freq=960000 }
    cpu2{ online=1 scaling_cur_freq=1958400 cpuinfo_max_freq=1958400 cpuinfo_min_freq=960000 }
    cpu3{ online=1 scaling_cur_freq=1958400 cpuinfo_max_freq=1958400 cpuinfo_min_freq=960000 }
    cpu4{ online=1 scaling_cur_freq=768000 cpuinfo_max_freq=1459200 cpuinfo_min_freq=768000 }
    cpu5{ online=1 scaling_cur_freq=768000 cpuinfo_max_freq=1459200 cpuinfo_min_freq=768000 }
    cpu6{ online=1 scaling_cur_freq=768000 cpuinfo_max_freq=1459200 cpuinfo_min_freq=768000 }
    cpu7{ online=1 scaling_cur_freq=768000 cpuinfo_max_freq=1459200 cpuinfo_min_freq=768000 }
    CPU usage from 0ms to 8302ms later (2020-06-03 10:24:42.652 to 2020-06-03 10:24:50.953):

**Comment by xuexirong** [comment]
@DeathLove4 不要用mediaplayer，用ijk或者exo

**Comment by xuexirong** [comment]
@wywangyunying 不要用mediaplayer，用ijk或者exo试试
