### ISSUE TITLE
抖音模式中播放的时候会闪一下黑屏请问大概是哪里出现问题了呢

### ISSUE THREAD

**Issue by object1984** [Doikki/DKVideoPlayer#538]

**Comment by fishflay** [comment]
我用exo内核播放也遇到了闪屏问题，开始播放的时候会闪一下。我通过自定义RenderView重写MeasureHelper.doMeasure方法，在未获取到视频宽高的时候view宽高返回0，避免黑屏闪烁

不知道有没有更好方法

**Comment by x8-phoenix** [comment]
初始化的时候代码写了
mPlayerContainer.setBackgroundColor(Color.BLACK);
改成Color.TRANSPARENT
试试，我的改完是没问题了

**Comment by folinwu2296** [comment]
抖音模式，高度   1280的视频切到  高度为 480的视频，播放的时候会闪一下，这个怎么处理啊

**Comment by chenkexu** [comment]
>有没有具体的代码啊？

**Comment by appdev** [comment]
2023 年，exo 问题在华为、荣耀手机上还有问题，楼上代码可用，但是有个问题，部分手机写0 会导致接下来不会调用，写1 可以
