### ISSUE TITLE
抖音模式中播放的时候,拖动进度条经常发生ANR

### ISSUE THREAD

**Issue by wywangyunying** [Doikki/DKVideoPlayer#539]
抖音模式中播放的时候,拖动进度条经常发生ANR，求大神能解惑

**Comment by Doikki** [comment]
demo能否复现

**Comment by wywangyunying** [comment]
demo中抖音模式没有进度条展示功能，我的项目中按照你的自己添加的，
TikTokView看附件


wywangyunying@163.com
 
发件人： Doikki
发送时间： 2020-06-12 14:24
收件人： Doikki/DKVideoPlayer
抄送： wywangyunying; Author
主题： Re: [Doikki/DKVideoPlayer] 抖音模式中播放的时候,拖动进度条经常发生ANR (#539)
demo能否复现

**Comment by Doikki** [comment]
GitHub回复我

**Comment by wywangyunying** [comment]
demo中抖音模式没有进度条展示功能，我的项目中按照你的自己添加的，

**Comment by wywangyunying** [comment]
public class TikTokView extends FrameLayout implements IControlComponent, SeekBar.OnSeekBarChangeListener {

    private ImageView thumb;
    private ImageView mPlayBtn;

    private SeekBar mVideoProgress;
    private LinearLayout mBottomContainer;
    private TextView mTotalTime, mCurrTime;
    private ProgressBar mLoading;
    private boolean mIsDragging;

    private ControlWrapper mControlWrapper;
    private int mScaledTouchSlop;
    private int mStartX, mStartY;

    private Context mContext;
    private onItemChildClick onItemChildClickListener;
    private GestureDetector mGestureDetector;
    float[] num = {-30, -20, 0, 20, 30};//随机心形图片角度
    long[] mHits = new long[2];

    public TikTokView(@NonNull Context context) {
        super(context);
        initView(context);
    }

    public TikTokView(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        initView(context);
    }

    public TikTokView(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        initView(context);
    }

    private void initView(Context context) {
        this.mContext = context;
        mGestureDetector = new GestureDetector(mContext, new OnDoubleClick());
    }

    {
//        setVisibility(GONE);
        LayoutInflater.from(getContext()).inflate(R.layout.layout_tiktok_controller, this, true);
        thumb = findViewById(R.id.iv_thumb);

        mBottomContainer = findViewById(R.id.bottom_container);
        mVideoProgress = findViewById(R.id.seekBar);
        mVideoProgress.setOnSeekBarChangeListener(this);
        mTotalTime = findViewById(R.id.total_time);
        mCurrTime = findViewById(R.id.curr_time);
        mLoading = findViewById(R.id.loading);
        mVideoProgress.setProgress(0);
        mVideoProgress.setSecondaryProgress(0);
        mBottomContainer.setVisibility(GONE);

        mPlayBtn = findViewById(R.id.play_btn);
        setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                mControlWrapper.togglePlay();
            }
        });
        mScaledTouchSlop = ViewConfiguration.get(getContext()).getScaledTouchSlop();

        //5.1以下系统SeekBar高度需要设置成WRAP_CONTENT
        if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.LOLLIPOP_MR1) {
            mVideoProgress.getLayoutParams().height = ViewGroup.LayoutParams.WRAP_CONTENT;
        }
    }

    @Override
    public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
        if (!fromUser) {
            return;
        }

        long duration = mControlWrapper.getDuration();
        long newPosition = (duration * progress) / mVideoProgress.getMax();
        if (mCurrTime != null)
            mCurrTime.setText(stringForTime((int) newPosition));
    }

    @Override
    public void onStartTrackingTouch(SeekBar seekBar) {
        mIsDragging = true;
        mControlWrapper.stopProgress();
        mControlWrapper.stopFadeOut();
    }

    @Override
    public void onStopTrackingTouch(SeekBar seekBar) {
        long duration = mControlWrapper.getDuration();
        long newPosition = (duration * seekBar.getProgress()) / mVideoProgress.getMax();
        mControlWrapper.seekTo((int) newPosition);
        mIsDragging = false;
        mControlWrapper.startProgress();
        mControlWrapper.startFadeOut();
    }

    public class OnDoubleClick extends GestureDetector.SimpleOnGestureListener {
        @Override
        public boolean onDoubleTap(MotionEvent e) { //双击
            if (onItemChildClickListener != null) {
                final ImageView imageView = new ImageView(mContext);
                RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(100, 100);
                params.leftMargin = (int) e.getX() - 100;
                params.topMargin = (int) e.getY() - 100;
                imageView.setImageDrawable(getResources().getDrawable(R.drawable.tiktok_star_selected));
                imageView.setLayoutParams(params);
                addView(imageView);

                AnimatorSet animatorSet = new AnimatorSet();
                animatorSet.play(scale(imageView, "scaleX", 2f, 0.9f, 100, 0))//缩放动画，X轴2倍缩小至0.9倍
                        .with(scale(imageView, "scaleY", 2f, 0.9f, 100, 0))//缩放动画，Y轴2倍缩小至0.9倍
                        .with(rotation(imageView, 0, 0, num[new Random().nextInt(4)]))//旋转动画，随机旋转角度num={-30.-20，0，20，30}
                        .with(alpha(imageView, 0, 1, 100, 0))//渐变透明度动画，透明度从0-1.
                        .with(scale(imageView, "scaleX", 0.9f, 1, 50, 150))//缩放动画，X轴0.9倍缩小至1倍
                        .with(scale(imageView, "scaleY", 0.9f, 1, 50, 150))//缩放动画，Y轴0.9倍缩小至1倍
                        .with(translationY(imageView, 0, -600, 800, 400))//平移动画，Y轴从0向上移动600单位
                        .with(alpha(imageView, 1, 0, 300, 400))//透明度动画，从1-0
                        .with(scale(imageView, "scaleX", 1, 3f, 700, 400))//缩放动画，X轴1倍放大至3倍
                        .with(scale(imageView, "scaleY", 1, 3f, 700, 400));//缩放动画，Y轴1倍放大至3倍

                animatorSet.start();
                animatorSet.addListener(new AnimatorListenerAdapter() {
                    @Override
                    public void onAnimationEnd(Animator animation) {
                        super.onAnimationEnd(animation);
                        removeViewInLayout(imageView);
                    }
                });
                onItemChildClickListener.onTouchPraiseClick(e);
            }
            return false;
        }

        public boolean onSingleTapConfirmed(MotionEvent event) { //单击
            int action = event.getAction();
            switch (action) {
                case MotionEvent.ACTION_DOWN:
                    mStartX = (int) event.getX();
                    mStartY = (int) event.getY();
                case MotionEvent.ACTION_UP:
                    int endX = (int) event.getX();
                    int endY = (int) event.getY();
                    if (Math.abs(endX - mStartX) < mScaledTouchSlop
                            && Math.abs(endY - mStartY) < mScaledTouchSlop) {
                        performClick();
                    }
                    break;
            }
            return false;
        }
    }

    /**
     * 解决点击和VerticalViewPager滑动冲突问题
     */
    @Override
    public boolean onTouchEvent(MotionEvent event) {
        mGestureDetector.onTouchEvent(event);
        return true;
    }

    @Override
    public void attach(@NonNull ControlWrapper controlWrapper) {
        mControlWrapper = controlWrapper;
    }

    @Override
    public View getView() {
        return this;
    }

    @Override
    public void onVisibilityChanged(boolean isVisible, Animation anim) {

    }

    @Override
    public void onPlayStateChanged(int playState) {
        switch (playState) {
            case VideoView.STATE_IDLE:
                L.e("STATE_IDLE " + hashCode());
                thumb.setVisibility(VISIBLE);
                mPlayBtn.setVisibility(VISIBLE);
                mLoading.setVisibility(GONE);
                break;
            case VideoView.STATE_PLAYBACK_COMPLETED:
//                setVisibility(GONE);
                mVideoProgress.setProgress(0);
                mVideoProgress.setSecondaryProgress(0);
                break;
            case VideoView.STATE_START_ABORT:
            case VideoView.STATE_PREPARING:
                mPlayBtn.setVisibility(GONE);
                mLoading.setVisibility(VISIBLE);
                mVideoProgress.setProgress(0);
                mVideoProgress.setSecondaryProgress(0);
                mTotalTime.setText("00:00");
                break;
            case VideoView.STATE_PREPARED:
                L.e("STATE_PREPARED " + hashCode());
                mPlayBtn.setVisibility(GONE);
                mLoading.setVisibility(GONE);
                break;
            case VideoView.STATE_ERROR:
                L.e("STATE_ERROR " + hashCode());
                ToastUtil.toast(R.string.dkplayer_error_message);
                mLoading.setVisibility(GONE);
                mPlayBtn.setVisibility(GONE);
                mControlWrapper.stopProgress();
                mControlWrapper.stopFadeOut();
//                setVisibility(GONE);
                break;
            case VideoView.STATE_PLAYING:
                L.e("STATE_PLAYING " + hashCode());
                thumb.setVisibility(GONE);
                mPlayBtn.setVisibility(GONE);
                mLoading.setVisibility(GONE);
                mVideoProgress.setProgress(0);
                mVideoProgress.setSecondaryProgress(0);
                mBottomContainer.setVisibility(VISIBLE);
//                setVisibility(VISIBLE);
                //开始刷新进度
                mControlWrapper.startProgress();
//                mControlWrapper.startFadeOut();
                break;
            case VideoView.STATE_PAUSED:
                L.e("STATE_PAUSED " + hashCode());
                thumb.setVisibility(GONE);
                mLoading.setVisibility(GONE);
                mPlayBtn.setVisibility(VISIBLE);
                mControlWrapper.stopProgress();
                mControlWrapper.stopFadeOut();
                break;
            case VideoView.STATE_BUFFERING:
                mPlayBtn.setVisibility(GONE);
                mLoading.setVisibility(VISIBLE);
                mControlWrapper.stopProgress();
                mControlWrapper.stopFadeOut();
                break;
            case VideoView.STATE_BUFFERED:
                mPlayBtn.setVisibility(GONE);
                mLoading.setVisibility(GONE);
                mControlWrapper.startProgress();
                mControlWrapper.startFadeOut();
                break;
        }
    }

    @Override
    public void onPlayerStateChanged(int playerState) {

    }

    @Override
    public void setProgress(int duration, int position) {
        if (mIsDragging) {
            return;
        }

        if (mVideoProgress != null) {
            if (duration > 0) {
                mVideoProgress.setEnabled(true);
                int pos = (int) (position * 1.0 / duration * mVideoProgress.getMax());
                mVideoProgress.setProgress(pos);
            } else {
                mVideoProgress.setEnabled(false);
            }
            int percent = mControlWrapper.getBufferedPercentage();
            if (percent >= 95) { //解决缓冲进度不能100%问题
                mVideoProgress.setSecondaryProgress(mVideoProgress.getMax());
            } else {
                mVideoProgress.setSecondaryProgress(percent * 10);
            }
        }

        if (mTotalTime != null)
            mTotalTime.setText(stringForTime(duration));
        if (mCurrTime != null)
            mCurrTime.setText(stringForTime(position));
    }

    @Override
    public void onLockStateChanged(boolean isLocked) {
    }

    public void setItemChildClick(onItemChildClick listener) {
        this.onItemChildClickListener = listener;
    }

    public interface onItemChildClick {
        void onTouchPraiseClick(MotionEvent event);
    }

    public static ObjectAnimator scale(View view, String propertyName, float from, float to, long time, long delayTime) {
        ObjectAnimator translation = ObjectAnimator.ofFloat(view, propertyName, from, to);
        translation.setInterpolator(new LinearInterpolator());
        translation.setStartDelay(delayTime);
        translation.setDuration(time);
        return translation;
    }

    public static ObjectAnimator translationX(View view, float from, float to, long time, long delayTime) {
        ObjectAnimator translation = ObjectAnimator.ofFloat(view, "translationX", from, to);
        translation.setInterpolator(new LinearInterpolator());
        translation.setStartDelay(delayTime);
        translation.setDuration(time);
        return translation;
    }

    public static ObjectAnimator translationY(View view, float from, float to, long time, long delayTime) {
        ObjectAnimator translation = ObjectAnimator.ofFloat(view, "translationY", from, to);
        translation.setInterpolator(new LinearInterpolator());
        translation.setStartDelay(delayTime);
        translation.setDuration(time);
        return translation;
    }

    public static ObjectAnimator alpha(View view, float from, float to, long time, long delayTime) {
        ObjectAnimator translation = ObjectAnimator.ofFloat(view, "alpha", from, to);
        translation.setInterpolator(new LinearInterpolator());
        translation.setStartDelay(delayTime);
        translation.setDuration(time);
        return translation;
    }

    public static ObjectAnimator rotation(View view, long time, long delayTime, float... values) {
        ObjectAnimator rotation = ObjectAnimator.ofFloat(view, "rotation", values);
        rotation.setDuration(time);
        rotation.setStartDelay(delayTime);
        rotation.setInterpolator(input -> input);
        return rotation;
    }
}

**Comment by wywangyunying** [comment]
感觉是    mControlWrapper.startProgress();和mControlWrapper.startFadeOut();引起的，后来我在onPlayStateChanged方法中对每个状态都mControlWrapper.stopProgress();和 mControlWrapper.stopFadeOut();，ANR问题减少了，但是频繁看新视频和拖动进度条，偶尔还是会ANR

**Comment by Doikki** [comment]
mControlWrapper.stopFadeOut();你知道这是干嘛用的嘛

**Comment by wywangyunying** [comment]
取消上次的计时线程吗

**Comment by Doikki** [comment]
你看看源码里的注释

**Comment by wywangyunying** [comment]
你的意思是我不应该在onPlayStateChanged中对各个状态进行判断然后调用startFadeOut();和stopFadeOut()吗
