### ISSUE TITLE
仿抖音播放，如果在播放fragment 中出现键盘吊起，再刷新视频 ，将会出现黑屏

### ISSUE THREAD

**Issue by jplayer-top** [Doikki/DKVideoPlayer#541]

**Comment by Doikki** [comment]
不要让activity重走生命周期

**Comment by jplayer-top** [comment]
你好，我试过将Viewpage2 的仿抖音播放视频放在 Activity中播放，然后弹起键盘，这种情况是没有问题的


但是如果 将Viewpage2 的仿抖音播放视频放在Fragment 中播放，然后弹起键盘，这种情况是会出现播放黑屏只有音频没有视频，这个时候并没有走生命周期啊


jplayer_top@163.com
 
发件人： Doikki
发送时间： 2020-06-12 14:20
收件人： Doikki/DKVideoPlayer
抄送： oblivion; Author
主题： Re: [Doikki/DKVideoPlayer] 仿抖音播放，如果在播放fragment 中出现键盘吊起，再刷新视频 ，将会出现黑屏 (#541)
不要让activity重走生命周期

**Comment by jplayer-top** [comment]
不只是ViewPage2，三个仿抖音播放的功能只要放入到fragment中，出现键盘弹起，上滑下滑视频后的视频是黑屏，只有声音
