### ISSUE TITLE
ANR 问题

### ISSUE THREAD

**Issue by wywangyunying** [Doikki/DKVideoPlayer#542]
参考抖音的demo，在TikTokView中添加了一个进度条
![image](https://user-images.githubusercontent.com/29906269/83987041-7a829c00-a971-11ea-9e1f-be92bec619cb.png)
![image](https://user-images.githubusercontent.com/29906269/83987059-8a9a7b80-a971-11ea-9076-950423f4fa9f.png)
![image](https://user-images.githubusercontent.com/29906269/83987067-92f2b680-a971-11ea-90d3-bb60357285ae.png)
但是多次上滑播放新视频并拖动进度条，就会出现ANR，问题出现在mControlWrapper.startProgress();请问作者有解决办法吗

**Comment by xuexirong** [comment]
@wywangyunying 我遇到了同样的问题，您解决了么
