### ISSUE TITLE
BaseVideoController 中没有了 doStartStopFullScreen 横竖屏切换，如何处理横屏全屏返回？？？

### ISSUE THREAD

**Issue by zj2050** [Doikki/DKVideoPlayer#543]
activity 横屏状态下打开播放器到全屏状态，播放器从全屏返回后，activity变成竖屏了， 如何保持全屏返回后 activity 横屏状态不变

**Comment by zj2050** [comment]
https://github.com/Doikki/DKVideoPlayer/issues/124
这个帖子对应的方案中没有 对应方法， 而不到断点  stopFullScreen

**Comment by zj2050** [comment]
@Doikki @ansnail 请指点一下，pad必须横屏使用， 全屏返回怎么都进入竖屏模式，在BaseVideoController  无法设置断点， 自定义 MyVideoController extends StandardVideoController
重载     @Override
    protected boolean stopFullScreen() {
        return super.stopFullScreen();
    }

也不能断点

**Comment by Doikki** [comment]
我demo里有pad的演示啊
