### ISSUE TITLE
刷新问题

### ISSUE THREAD

**Issue by zh793060640** [Doikki/DKVideoPlayer#549]
现在是我再其他页面做了操作，需要刷新adapter里面的内容，刷新用的是notifyItemRangeChanged方法，然后再返回到视频播放页面，视频有声音，但是画面没东，不晓得是哪个的问题。

**Comment by devzwy** [comment]
请问问题解决了吗？我这边也碰到了。刷新后页面数据变了，但是加载了缩略图遮挡了视频，点击奔溃

**Comment by zh793060640** [comment]
没有，感觉这个框架问题还是多------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Jason&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月29日(星期二) 下午3:42
收件人:&nbsp;&quot;Doikki/DKVideoPlayer&quot;<DKVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;&quot;zh793060640&quot;<793060640@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Doikki/DKVideoPlayer] 刷新问题 (#549)

**Comment by devzwy** [comment]
> 没有，感觉这个框架问题还是多------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;Jason&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年9月29日(星期二) 下午3:42 收件人:&nbsp;&quot;Doikki/DKVideoPlayer&quot;<DKVideoPlayer@noreply.github.com&gt;; 抄送:&nbsp;&quot;zh793060640&quot;<793060640@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Doikki/DKVideoPlayer] 刷新问题 (#549)

嗯，发现了。数据源没法刷新的问题会有好多后遗症，我碰到了好多问题。准备找替换方案了，还好这个坑陷的不深，老哥有没有好的替换方案？
