### ISSUE TITLE
大佬们 SeamlessPlayFragment不能复用，怎么改啊

### ISSUE THREAD

**Issue by jiahairan123** [Doikki/DKVideoPlayer#551]

**Comment by Doikki** [comment]
demo多看几遍

**Comment by jiahairan123** [comment]
> demo多看几遍 博主你好，我看Demo 看了很久了，可能我水平不太够。我试过懒加载，没有解决问题。

**Comment by jiahairan123** [comment]
> demo多看几遍
还试过 添加多个 getVideoViewManager().add(mVideoView, Tag.SEAMLESS);
                            getVideoViewManager().add(mVideoView, Tag.SEAMLESS222);
希望您能帮忙分析，给个思路。从哪里入手解决这个问题
