### ISSUE TITLE
关于android 8.0 画中画问题

### ISSUE THREAD

**Issue by shoushuai** [Doikki/DKVideoPlayer#555]
操作流程：打开demo页面，点开悬浮窗，点窗口的全屏，然后home到桌面，点App，发现demo页面消失了，这是什么原因，系统应该就是这样，我看爱奇艺也是这个问题。

我遇到的问题，我有一个直播列表，第一个经过上面流程，再打开第二个，播放的还是第一个视频，应该没释放掉上个页面的视频

**Comment by Doikki** [comment]
系统可能就是这样处理的
