### ISSUE TITLE
没有画面

### ISSUE THREAD

**Issue by booldplx** [Doikki/DKVideoPlayer#558]
用的是2.5.7版本, 测试链接 http://api-pre1.430dj.com/news/cb8c82d5f6d01cf1c36d7c57935996da.mp4 有声音和进度条,没有画面,以前一直是可以的,今天不知道怎么了,换版本的话,修改的地方太多了一些

**Comment by booldplx** [comment]
老版本的是不是不能用了?  我以前下载的代码刚编译运行了一下,全部不能播放了

**Comment by ZhengXiaolongGitHub** [comment]
请问您这个问题修复了吗？
