### ISSUE TITLE
设置静音不起作用

### ISSUE THREAD

**Issue by linlongjanny39** [Doikki/DKVideoPlayer#563]
setMute(true) 以及 setVolume(0.0f, 0.0f) 都是不生效的，在demo上测试了，也是一样的，是有别的设置静音的方式吗？

**Comment by Wdzxx007** [comment]
我也遇到了设置静音不起作用

**Comment by linlongjanny39** [comment]
设置静音的代码要写在播放之后，我也是醉了，看了源码，初始化是MideaPlayer是放在start()方法中的



linlongjie@xiangrikui.com
 
发件人： JhonStar
发送时间： 2020-08-04 10:12
收件人： Doikki/DKVideoPlayer
抄送： linlongjanny39; Author
主题： Re: [Doikki/DKVideoPlayer] 设置静音不起作用 (#563)
我也遇到了设置静音不起作用

**Comment by Wdzxx007** [comment]
> 设置静音的代码要写在播放之后，我也是醉了，看了源码，初始化是MideaPlayer是放在start()方法中的 linlongjie@xiangrikui.com 发件人： JhonStar 发送时间： 2020-08-04 10:12 收件人： Doikki/DKVideoPlayer 抄送： linlongjanny39; Author 主题： Re: [Doikki/DKVideoPlayer] 设置静音不起作用 (#563) 我也遇到了设置静音不起作用 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢大佬

**Comment by MasterMvp** [comment]
> setMute(true) 以及 setVolume(0.0f, 0.0f) 都是不生效的，在demo上测试了，也是一样的，是有别的设置静音的方式吗？

将VideoView重写,其他不动,找到 onPrepared() 方法, 在里面加上 mMediaPlayer.setVolume(0f, 0f); 就可静音了,MediaPlayer也是如此,MediaPlayer 有setOnPreparedListener回调,

**Comment by Wdzxx007** [comment]
嗯嗯，十分感谢

**Comment by linlongjanny39** [comment]
或者在start之后调用



linlongjie@xiangrikui.com
 
发件人： MasterMvp
发送时间： 2020-12-01 15:49
收件人： Doikki/DKVideoPlayer
抄送： linlongjanny39; Author
主题： Re: [Doikki/DKVideoPlayer] 设置静音不起作用 (#563)
setMute(true) 以及 setVolume(0.0f, 0.0f) 都是不生效的，在demo上测试了，也是一样的，是有别的设置静音的方式吗？
将VideoView重写,其他不动,找到 onPrepared() 方法, 在里面加上 mMediaPlayer.setVolume(0f, 0f); 就可静音了,MediaPlayer也是如此,MediaPlayer 有setOnPreparedListener回调,

**Comment by Wdzxx007** [comment]
我现在是在start之后调用，完美解决，感谢大佬 @MasterMvp @linlongjanny39
