### ISSUE TITLE
视频播放状态不太准确

### ISSUE THREAD

**Issue by DancingSnowInFingertips** [Doikki/DKVideoPlayer#567]
问题：VideoView.STATE_PREPARED与VideoView.STATE_PLAYING不是无缝衔接的
现象：视频准备好后（VideoView.STATE_PREPARED），隐藏进度条和背景图片，会有1~2s的黑屏（应该是播放器默认背景）卡顿后才会播放
Demo里也有这个现象，不过很短，如果是个长视频就明显了

**Comment by Doikki** [comment]
在playing状态隐藏就好

**Comment by DancingSnowInFingertips** [comment]
嗯嗯，好的，现在项目里就是这样处理的，就是问问看有没有更优雅的方法
