### ISSUE TITLE
大佬 我想提个需求 就是可以自定义布局 或者更换ui样式啊 图标什么

### ISSUE THREAD

**Issue by itwangyong** [Doikki/DKVideoPlayer#569]
因为我一直在用你的这个库 但是我们的样式和你的不一样 所以每次我都是下载源码引入项目 然后修改ui
这样就有点太麻烦了 希望大佬可以提供接口替换ui样式 或者直接让我们自定义布局

**Comment by Doikki** [comment]
dkplayer-ui这个库你随便改
