### ISSUE TITLE
播放网络视频会出现ANR现象.

### ISSUE THREAD

**Issue by jjhappyforever** [Doikki/DKVideoPlayer#570]
问题：
        使用ijkPlayer播放器播放快速快进后退不会出现ANR现象.如果使用MediaPlayer播放网络视频，手势快速前进后退，则会出现无响应显现，是必现的，希望作者能改善下.
        该播放器挺好的，为作者点赞。

**Comment by jjhappyforever** [comment]
希望作者能关注下此问题.

**Comment by Doikki** [comment]
不建议使用mediaplayer，推荐exo
