### ISSUE TITLE
如何关闭IJKMEDIA的日志

### ISSUE THREAD

**Issue by KunNiu** [Doikki/DKVideoPlayer#576]
已经全局设置了 setLogEnable(false);
但还是有IJKMEDIA的日志
 D/IJKMEDIA: FFP_MSG_VIDEO_SEEK_RENDERING_START:
 D/IJKMEDIA: FFP_MSG_BUFFERING_START:
 D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
 D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:

**Comment by Doikki** [comment]
无法彻底关闭
