### ISSUE TITLE
关于适配器刷新问题，有遇到的进来探讨下

### ISSUE THREAD

**Issue by devzwy** [Doikki/DKVideoPlayer#579]
问题1:数据源无法replce，只能clear后 做add 或 addAll操作。
问题2:当页面单条item数据变动后需要刷新时，notfiDataChanged函数失效。
请问大佬们怎么处理的呢？

**Comment by adapana** [comment]
Use notifyiteminserted()

**Comment by devzwy** [comment]
> Use notifyiteminserted()

更新原数据不行
