### ISSUE TITLE
播放部分本地视频文件失败

### ISSUE THREAD

**Issue by jerry9433** [Doikki/DKVideoPlayer#588]
目前使用为3.2.6版本，且此问题必现
exo、ijk均会出现这样的问题，mediaplayer没试过
eg : 
视频A路径:/storage/emulated/0/DCIM/pipixia/65cafeff2ac31fbf39de67ca8619acd4.mp4 
结果：正常播放

视频B路径:/storage/emulated/0/DCIM/pipixia/65cafeff2ac31fbf39de67ca8619acd4#$.mp4
结果：播放失败，Log打印找不到路径，且该路径截取掉了后面的#$.mp4
上图
![image](https://user-images.githubusercontent.com/31622465/96851063-2e507800-148a-11eb-90d9-6b6b207c307b.png)
![image](https://user-images.githubusercontent.com/31622465/96851082-34465900-148a-11eb-8fe6-4163b35a23e0.png)

**Comment by Doikki** [comment]
着我没办法，只能你自己去杜绝这种特殊字符
