### ISSUE TITLE
播放部分视频时无法播放,播放错误

### ISSUE THREAD

**Issue by lxlfpeng** [Doikki/DKVideoPlayer#591]
将地址替换为如下地址:
https://a1.easemob.com/1103190506055483/kandoudou/chatfiles/929d83e0-19ba-11eb-aa7f-0b8633f0eaf7
结果为:

![微信图片_20201029161709](https://user-images.githubusercontent.com/13760574/97543197-dc1bd380-1a02-11eb-8489-36eea515198e.jpg)

ijk播放器黑屏,无法播放
设备 mix2 android 9

**Comment by Doikki** [comment]
地址过期了
