### ISSUE TITLE
activity禁止了横屏，还是会自动进入全屏模式问题

### ISSUE THREAD

**Issue by windyer39** [Doikki/DKVideoPlayer#592]
activity禁止了横屏，但是手机放到桌面上，偶尔（不是百分百）会自动进入全屏播放模式。找了半天没找到哪里设置的。好像设置自动横屏的方法也被屏蔽了。 有什么地方可以解决这个问题吗

**Comment by Doikki** [comment]
要通过我提供的方法禁用

**Comment by pkxutao** [comment]
@Doikki 你好，请问你提供的禁用方法在哪里？ 找了wiki  demo都没找到。。。
@windyer39 请问你找到了没

**Comment by pkxutao** [comment]
找到了。。。controller.setEnableOrientation(true)就行了
