### ISSUE TITLE
怎么设置全屏的时候根据视频的宽高适应的播放视频

### ISSUE THREAD

**Issue by JoesWeek** [Doikki/DKVideoPlayer#594]
比如电视电影类的视频在全屏的时候是横屏播放，手机竖直拍摄的视频在全屏的时候竖直播放。

**Comment by Doikki** [comment]
看我控制器的代码，我有提供方法实现

**Comment by mz5210** [comment]
> 看我控制器的代码，我有提供方法实现
您好，找了下没有看到您说的这个方法，可以帮忙明确一下是哪个方法么？
