### ISSUE TITLE
请教一下有没有谁在导入 exo 出现问题的，如内容所示

### ISSUE THREAD

**Issue by Hunteryx** [Doikki/DKVideoPlayer#595]
因为要播放amr文件，加上三星手机MedioPlayer不支持，所以只能用exo了。
根据官网流程，导入
implementation 'com.github.dueeeke.dkplayer:player-exo:3.2.6'

导入成功但是编译过程中 报这个错误。
Caused by: java.lang.ClassNotFoundException: Class com.google.android.exoplayer2.ExoPlayer$EventListener not found

Process 'command 'E:\java\jdk1.8.0_261\bin\java.exe'' finished with non-zero exit value 1

**Comment by Doikki** [comment]
升级Java8
