### ISSUE TITLE
两个库的代码神似，不同的作者

### ISSUE THREAD

**Issue by qwertxyz** [Doikki/DKVideoPlayer#598]
- https://github.com/Doikki/DKVideoPlayer
![https://github.com/Doikki/DKVideoPlayer](https://user-images.githubusercontent.com/6167082/98891571-74bd5380-24d9-11eb-96cf-fa88bcb253cf.png)

- https://github.com/yangchong211/YCVideoPlayer
![https://github.com/yangchong211/YCVideoPlayer](https://user-images.githubusercontent.com/6167082/98891505-4ccdf000-24d9-11eb-9e6d-aa7281cfc984.png)

**Comment by Doikki** [comment]
他是基于我很老的一个版本修改的
