### ISSUE TITLE
Activity destroy timeout for ActivityRecord

### ISSUE THREAD

**Issue by GavinKai225** [Doikki/DKVideoPlayer#607]
弱网环境使用AndroidMediaPlayerFactory解码播放视频，播放一段视频后卡主，按返回键
12-11 10:02:59.179 D/nubialog(21953): onTransact android.media.MediaHTTPConnection:3 delay=689
12-11 10:02:59.226 W/ActivityTaskManager( 1641): Activity destroy timeout for ActivityRecord
12-11 10:02:59.226 V/ActivityTaskManager( 1641): Calling mServicetracker.OnActivityStateChange with flag truestateDESTROYED
12-11 10:02:59.227 V/ActivityTaskManager( 1641): Calling mServicetracker.OnActivityStateChange with flag falsestateDESTROYED

**Comment by Doikki** [comment]
不推荐使用系统mediaplayer，兼容性无法保证。推荐使用exo或者ijk
