### ISSUE TITLE
demo的无缝播放，跳转到播放详情后，锁屏或者按Home键回桌面，再次进demo  然后返回，列表的视频会黑掉。

### ISSUE THREAD

**Issue by HopeZZZ** [Doikki/DKVideoPlayer#609]
这是demo里也存在的一个bug，复现方式：
1.打开无缝播放列表
2.点击跳转到播放详情
3.锁屏（或者按Home键）
4.再次进入demo，点击返回键

原来播放的视频，就会黑掉。

**Comment by HopeZZZ** [comment]
Android10 特有的问题

**Comment by HopeZZZ** [comment]
已解决

**Comment by 278918014** [comment]
请问，你是如何解决的？可以给我们说一下吗？

**Comment by HopeZZZ** [comment]
> 请问，你是如何解决的？可以给我们说一下吗？

我已经提交PR了，等待作者合并代码就可以。Android10 Activity的onStop方法会导致共享元素动画失效，通过反射注入恢复共享元素动画就可以了

**Comment by 278918014** [comment]
好的，多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HopeZZZ"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 上午10:28
收件人: "Doikki/DKVideoPlayer"<DKVideoPlayer@noreply.github.com&gt;; 
抄送: "单纯哒记忆.."<278918014@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Doikki/DKVideoPlayer] demo的无缝播放，跳转到播放详情后，锁屏或者按Home键回桌面，再次进demo  然后返回，列表的视频会黑掉。 (#609)





  
请问，你是如何解决的？可以给我们说一下吗？
  
我已经提交PR了，等待作者合并代码就可以。Android10 Activity的onStop方法会导致共享元素动画失效，通过反射注入恢复共享元素动画就可以了
