### ISSUE TITLE
有没有截取gif图功能

### ISSUE THREAD

**Issue by zs18340282344** [Doikki/DKVideoPlayer#618]

**Comment by Doikki** [comment]
没有

**Comment by zs18340282344** [comment]
之后会更新这个功能吗？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Doikki&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月28日(星期一) 晚上9:48
收件人:&nbsp;&quot;Doikki/DKVideoPlayer&quot;<DKVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;&quot;zs18340282344&quot;<1477637339@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Doikki/DKVideoPlayer] 有没有截取gif图功能 (#618)

**Comment by Doikki** [comment]
不会，我不再更新了
