### ISSUE TITLE
怎么使用设置某些使用缓存，某些不使用缓存

### ISSUE THREAD

**Issue by byc4426** [Doikki/DKVideoPlayer#626]
怎么使用设置某些使用缓存，某些不使用缓存

**Comment by qiaoyhh** [comment]
找到某些的特征，使用缓存的调用， HttpProxyCacheServer cacheServer = ProxyVideoCacheManager.getProxy(this);
        String proxyUrl = cacheServer.getProxyUrl(DataUtil.SAMPLE_URL);反之不调用。。
