### ISSUE TITLE
exoplayer 2.12.0 版本中没有Util.getLooper()方法

### ISSUE THREAD

**Issue by hyr0318** [Doikki/DKVideoPlayer#641]
DK 视频库用到得exoplayer版本还是2.11.3，但是exoplayer新版本中已经没有Util.getLooper()这个方法了，由于项目中音频得库同时使用到了exoplayer，音频库中得exo版本是高版本得，DK 中就会报错，可以升级下支持最新得exo版本么 ？

**Comment by Doikki** [comment]
已经升级，请使用3.3.0版
