### ISSUE TITLE
这个播放器到底怎么使用的？我卡在了添加布局之后

### ISSUE THREAD

**Issue by nikolamakin** [Doikki/DKVideoPlayer#651]
1.我引入了我需要的包在.gradle文件中
2.添加布局
<com.dueeeke.videoplayer.player.VideoView
        android:id="@+id/player"
        android:layout_width="match_parent"
        android:layout_height="300dp" />

3.设置视频地址、控制器等
videoView.setUrl(URL_VOD); //设置视频地址
StandardVideoController controller = new StandardVideoController(this); 
controller.addDefaultControlComponent("标题", false);
videoView.setVideoController(controller); //设置控制器
videoView.start(); //开始播放，不调用则不自动播放

**那么问题来了，在第三步之前videoView 是绑定谁的？为何wiki上没有举例，本来就是初学安卓者，看你的demo看的云里雾里的，我只想要一个简单的播放场景，望谁能帮我一下，我看了GSYvideo 和 jiaoziVideo 他们都有如何一步一步绑定到播放器并使用的范例。感谢回答**

**Comment by yecaler** [comment]
哈哈哈哈，交钱，我远程帮你搞
