### ISSUE TITLE
建议android原生MediaPlayer在调release()和reset()之前都调一次stop()，否则容易ANR。

### ISSUE THREAD

**Issue by tydqcjj** [Doikki/DKVideoPlayer#656]
被测试测出好多次ANR，都跟MediaPlayer有关。总感觉原生的不好用。

**Comment by lishangwl** [comment]
> 被测试测出好多次ANR，都跟MediaPlayer有关。总感觉原生的不好用。

android原生MediaPlayer，我也是，确实会anr，不知道加了stop会不会好点

**Comment by Doikki** [comment]
@tydqcjj 这方法确定有效？

**Comment by tydqcjj** [comment]
> @tydqcjj 这方法确定有效？

https://www.cnblogs.com/yaya-Android/p/4519967.html
可以找一个码率高点的视频，播放时拖动进度，在视频还没有开始播放时，赶紧退出视频。这样应该能复现，我们公司项目就是这样复现的，修改后确实有效果。

**Comment by kyriej** [comment]
尤其是播放网络流 ，这个anr贼多
