### ISSUE TITLE
STATE_IDLE时为什么要移除所有private的Components

### ISSUE THREAD

**Issue by tydqcjj** [Doikki/DKVideoPlayer#657]
![image](https://user-images.githubusercontent.com/21003314/115701039-ed361380-a399-11eb-9380-db85c380797a.png)
如图调用了removeAllPrivateComponents。
我的项目是一个类似抖音滑动切换视频，切换下一个视频后，Component收不到回调，排查代码后定位到了removeAllPrivateComponents。
所以不太理解这样为什么要移除？

**Comment by Doikki** [comment]
你不要把Component设置成private不就行了

**Comment by tydqcjj** [comment]
我知道private设置为false就可以了。
