### ISSUE TITLE
缓存进度问题 

### ISSUE THREAD

**Issue by fuys123** [Doikki/DKVideoPlayer#664]
调用getBufferedPercentage（）缓存进度没有达到100的情况 不能准确判断缓存是否完成这么一个逻辑

**Comment by Doikki** [comment]
这个不是缓存进度

**Comment by fuys123** [comment]
> 这个不是缓存进度
那我如何判断缓存成功 ，我没找到这个api，应该给个缓存进度的回调接口。

**Comment by Doikki** [comment]
videocache有缓存进度的接口，你自己监听就好了

**Comment by fuys123** [comment]
> videocache有缓存进度的接口，你自己监听就好了

嗯嗯 我正回你呢， 处理好了 。
