### ISSUE TITLE
seekTo定位不准确

### ISSUE THREAD

**Issue by YangYaBin2007** [Doikki/DKVideoPlayer#674]
skipPositionWhenPlay((int) time); 视频总会后退几秒

**Comment by Doikki** [comment]
ijk 开启精准seek

**Comment by YangYaBin2007** [comment]
如何开启呢？
我的操作是 mMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);   但是进度播放的时候会有较长时间的黑屏

**Comment by Doikki** [comment]
还有一种方法就是提升视频关键帧的数量，ijk seek的原理是寻找视频中的关键帧，关键帧包含一帧完整的视频帧，无需解码器解码，所以比较快，打开精准seek之后，解码器会介入，所以比较慢
