### ISSUE TITLE
 exo 每次播放开启缓存，播放完毕可以清楚缓存么。因为缓存在的话，下一次打开会出错

### ISSUE THREAD

**Issue by SuperZhouyong** [Doikki/DKVideoPlayer#683]

**Comment by SuperZhouyong** [comment]
M3u8 的格式，用的 是CustomExoPlayerActivity 这个 demo. setCacheEnabled(true)  之后，多次开启就会出现错误

**Comment by SuperZhouyong** [comment]
M3u8 的格式，用的 是CustomExoPlayerActivity 这个 demo. setCacheEnabled(true)  之后，多次开启就会出现错误

**Comment by SuperZhouyong** [comment]
还得卸载，清理，才会缓存失效。只要设置 setCacheEnabled(false) 就很正常。 希望 楼主尽快优化 缓存清理，和缓存 读取的方法

**Comment by SuperZhouyong** [comment]
有个建议，能传入 缓存 目录是最好了

**Comment by SuperZhouyong** [comment]
具体什么问题不是很清楚。就是开启缓存之后，之后再看这个视频或者其他视频，一直报 读取缓存失败，手动删除缓存也有问题。用 github demo 也能复现这个问题。不开启缓存就没有这个问题。

**Comment by Adolphsa** [comment]
我也碰到这个问题了。

**Comment by Adolphsa** [comment]
不管是预加载还是缓存，多次重复打开就会出现只有声音正常播放，视频卡主不动的情况

**Comment by Doikki** [comment]
@SuperZhouyong @Adolphsa 可以自定义缓存的： ExoMediaSourceHelper 的setCache方法
