### ISSUE TITLE
打包时遇到报错：`xyz.doikki.videoplayer.player.AbstractPlayer` is missing

### ISSUE THREAD

**Issue by callhh** [Doikki/DKVideoPlayer#685]
Error: Default method desugaring of `xyz.doikki.videoplayer.exo.ExoMediaPlayer` failed because its super class `xyz.doikki.videoplayer.player.AbstractPlayer` is missing

**Comment by callhh** [comment]
![image](https://user-images.githubusercontent.com/17881472/126034515-d9644d14-cb2f-4ec2-8b53-14c0824bf9f8.png)

**Comment by callhh** [comment]
注释掉implementation 'xyz.doikki.android.dkplayer:player-exo:3.3.3' 这个 打包就没问题了，不知道是哪里问题？？？

**Comment by xuexirong** [comment]
@callhh 我也遇到这个问题了 您找到原因了么

**Comment by Doikki** [comment]
升级 apg 版本

**Comment by lazyjava** [comment]
什么是 升级 agp 版本？

**Comment by lazyjava** [comment]
> 升级 agp 版本

我也遇到了，不太理解

**Comment by SanYueSI** [comment]
把gradle版本换成>4
