### ISSUE TITLE
关于DKVideoPlayer

### ISSUE THREAD

**Issue by tydqcjj** [Doikki/DKVideoPlayer#686]
DKVideoPlayer是一个非常好的框架，我已经在多个项目上使用过了。尤其是IControlComponent的设计很好，搭配jetpack里的LifeCycle使用解耦业务非常棒。我是做OEM APP的，播放器需要和很多信号联动，现在借助IControlComponent可以把每个信号单独实现。首先非常感谢作者的开源，另外也想提点建议。
1、IControlComponent接口能否加上 boolean requestPlayer();方法，当所有IControlComponent都返回true才能播放。我目前的解决方案是在onPlayStateChanged里判断能不能播放，如果不能播放就暂停播放器。
2、能否支持自定义AudioFocusHelper，框架里AudioFocusHelper不适合我的业务。目前我的解决方案是用IControlComponent来实现AudioFocus逻辑。
3、播放器能否支持自定义StreamType，Google推荐Api 21是用setAudioAttributes。我不一定会用STREAM_MUSIC，有可能是我们设备上自己定义的StreamType。

**Comment by Doikki** [comment]
问题1：你要是实现什么样的需求，请具体描述下
问题2：用你这种方式是ok的
问题3：继承AndroidMediaPlayer扩展你自己的api，具体可参考demo中IjkVideoView和ExoVideoView

**Comment by tydqcjj** [comment]
> 问题1：你要是实现什么样的需求，请具体描述下
> 问题2：用你这种方式是ok的
> 问题3：继承AndroidMediaPlayer扩展你自己的api，具体可参考demo中IjkVideoView和ExoVideoView

我们设备上有很多信号，收到某些信号后代表这个时候不能播放了。所以想每次startPlay的时候判断下是否能播放。

**Comment by Doikki** [comment]
这个逻辑加在IControlComponent里不太合适吧，你可以灵活运用一下BaseVideoController里的showNetWarning这个接口，如果不能播放将该接口返回true就不会继续播放了

**Comment by Doikki** [comment]
具体做法就是写一个继承IControlComponent的接口，里面扩展 boolean requestPlayer();方法 然后再重写showNetWarning方法，遍历BaseVideoController的mControlComponents 这个集合，依次判断requestPlayer是否为true，如果全为true就让showNetWarning返回false让播放器正常播放

**Comment by tydqcjj** [comment]
非常感谢！
