### ISSUE TITLE
jar包冲突

### ISSUE THREAD

**Issue by changqk** [Doikki/DKVideoPlayer#695]
Duplicate class tv.danmaku.ijk.media.player.AbstractMediaPlayer found in modules jetified-ijkplayer-java-0.8.8-runtime.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8) and jetified-player-ijk-3.3.3-runtime.jar (xyz.doikki.android.dkplayer:player-ijk:3.3.3)

**Comment by Doikki** [comment]
升级一下agp版本
