### ISSUE TITLE
大佬，添加Header不正常，麻烦看一下

### ISSUE THREAD

**Issue by caoyi01** [Doikki/DKVideoPlayer#696]
![3e7d5bad954957c1c97de4bb15ce49f](https://user-images.githubusercontent.com/4277475/128452730-5f54ed08-1bd7-40b3-b200-d2b4eabd2c65.png)
![3df7e8578b8e394a9573b0cf6606c1d](https://user-images.githubusercontent.com/4277475/128452755-0f7824f6-a218-44f5-a69a-693f4b937bdd.png)
![9b162791ef73346859c803e42e30351](https://user-images.githubusercontent.com/4277475/128452876-18891d57-9c30-4598-82e4-decaead89cf0.png)
第一张图是未添加header，抓包的请求，第二张图是添加了header之后，第三张图是添加的header

**Comment by caoyi01** [comment]
1、出现两个UA，内容不一样
2、UA和Referer的值里面有key

**Comment by Doikki** [comment]
哪个播放器？最新版也是这样吗？

**Comment by caoyi01** [comment]
3.3.3、3.3.0、3.2.6 这三个版本都试了，一样

**Comment by Doikki** [comment]
哪个播放器

**Comment by caoyi01** [comment]
IjkPlayerFactory

**Comment by Doikki** [comment]
好，我下班调试一下

**Comment by caoyi01** [comment]
谢谢大佬 方便加个联系方式吗？282502139@qq.com 我邮箱

**Comment by Doikki** [comment]
加群找我

**Comment by caoyi01** [comment]
已申请，大佬调试的时候需要播放地址和header随时喊我

**Comment by caoyi01** [comment]
问题已解决，header的value前加空格即可
