### ISSUE TITLE
大佬,不支持avi格式吗

### ISSUE THREAD

**Issue by gsj913026743** [Doikki/DKVideoPlayer#697]
private void initVideo() {
        //设置播放加载路径
        mVideo.setUrl("android.resource://" + getPackageName() + "/" + R.raw.media);
        mVideo.setEnableMediaCodec(true);
        mVideo.setOnStateChangeListener(new VideoView.SimpleOnStateChangeListener() {
            @Override
            public void onPlayStateChanged(int playState) {
                //goActivity();
            }
        });
    }

   VideoViewManager.setConfig(VideoViewConfig.newBuilder()
                //使用使用IjkPlayer解码
                .setPlayerFactory(IjkPlayerFactory.create())
                .setPlayerFactory(ExoMediaPlayerFactory.create())
                .build());

**Comment by Doikki** [comment]
支持
