### ISSUE TITLE
当showNetWarning return 为true 时，视频无法播放的bug

### ISSUE THREAD

**Issue by nikolamakin** [Doikki/DKVideoPlayer#700]
//WIFI 网络开启；移动数据关闭
public boolean showNetWarning() {
        //不显示移动网络播放警告
        return false; //可以正常播放视频
        return true; //不播放视频,无任何错误输出
    }

我不知道这算不算bug，不过因为我想显示移动网络播放警告，便直接return true, 又改了其它代码，后来无法播放视频，我调试了一天代码....

**Comment by Doikki** [comment]
return true 之后要在监听state_start_abort实现自己的提示界面，具体可参照standardvideocontroller里面的实现
