### ISSUE TITLE
android9.0播放网络视频出现问题

### ISSUE THREAD

**Issue by androidzhangyu** [Doikki/DKVideoPlayer#701]
使用android9.0播放网络视频时，出现
MediaPlayer: Couldn't open https://xxx.com/upload/refer/2021-03/b0bcf79fa49a4b2ea1f1ac6b096a6424.mp4: java.io.FileNotFoundException: No content provider: https://xxx.com/upload/refer/2021-03/b0bcf79fa49a4b2ea1f1ac6b096a6424.mp4                      链接使用浏览器是可以正常播放的。

**Comment by tristanyi** [comment]
我也遇到了

**Comment by tristanyi** [comment]
你检查一下是不是播放前没有设置播放内核，我好像理解错了作者的意思，播放前我再次设置播放内核后，问题解决
