### ISSUE TITLE
关于音轨自己实现建议

### ISSUE THREAD

**Issue by mynameispp** [Doikki/DKVideoPlayer#708]
大佬，可以开放获取com.dueeeke.videoplayer.player.VideoView->mMediaPlayer 和com.dueeeke.videoplayer.ijk. IjkPlayer->mMediaPlayer 两个变量的方法吗，因为这两个变量是protected没法直接获取。若能开放可以让用户自己实现切换音轨的功能。希望能考虑下~

**Comment by Doikki** [comment]
继承一下ijkplayer扩展，可参考自定义ijkplayer demo

**Comment by mynameispp** [comment]
> 继承一下ijkplayer扩展，可参考自定义ijkplayer demo
好的，谢谢大佬。也给后面的同志一个方案，如果只想音轨切换，又不想重写ijkplayer。只需继承IjkPlayer，VideoView，PlayerFactory。改下里面的参数即可。
下面是测试代码
> public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        VideoViewManager.setConfig(VideoViewConfig.newBuilder()
                //使用使用自定义IjkPlayer解码
                .setPlayerFactory(MyVideoPlayerFactory.create())
                .build());
    }

> public class MyIjkPlayer extends IjkPlayer {
    public MyIjkPlayer(Context context) {
        super(context);
    }

    public void getTrackInfo() {
        //默认音轨
        int defaultAudio = mMediaPlayer.getSelectedTrack(ITrackInfo.MEDIA_TRACK_TYPE_AUDIO);
        Log.e("dddddddddd", "=====默认音轨====" + defaultAudio);
        IjkTrackInfo[] tackInfo = mMediaPlayer.getTrackInfo();
        for (IjkTrackInfo ijkTrackInfo : tackInfo) {
            Log.e("dddddddddd", String.format("=====音轨信息====" + ijkTrackInfo.toString()));
        }
    }
    public void setStract(int trackIndex) {
        //切换音轨。这里只写了切换音轨可能会有问题。
        mMediaPlayer.selectTrack(trackIndex);
    }

> public class MyVideoView extends VideoView<MyIjkPlayer> {
    public MyVideoView(@NonNull Context context) {
        super(context);
    }

    public MyVideoView(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
    }

    public MyVideoView(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);

    }

    public void getTrackInfo(){
        //获取音轨信息
        mMediaPlayer.getTrackInfo();
    }
    public void setStrack(int trackIndex) {
        //切换音轨。这里只写了切换音轨可能会有问题。
        mMediaPlayer.setStrack(trackIndex);
    }
}

> public class MyVideoPlayerFactory extends PlayerFactory<MyIjkPlayer> {
    public static MyVideoPlayerFactory create() {
        return new MyVideoPlayerFactory();
    }

    @Override
    public MyIjkPlayer createPlayer(Context context) {
        //返回自定义的IjkPlayer
        return new MyIjkPlayer(context);
    }
}
