### ISSUE TITLE
问一下怎么配合vr库使用   MDVRLibrary 

### ISSUE THREAD

**Issue by csh159** [Doikki/DKVideoPlayer#719]
可以实现Vr直播视频观看，看了下金山云视频播放器有个方法可以绑定，如下图
https://user-images.githubusercontent.com/4157414/135192710-dc5de65b-330c-438a-a78d-2871d59d4730.png

**Comment by Doikki** [comment]
你看一下自定义renderview可不可行，我对 vr sdk不太了解

**Comment by csh159** [comment]
好的，谢谢
