### ISSUE TITLE
带空格的链接都播放不成功是为啥，demo里用也是一样

### ISSUE THREAD

**Issue by ly469097645** [Doikki/DKVideoPlayer#722]
http://58.23.212.133:5065/tracing-source/file/1633918707834/冠浦路116号 2.m4a

**Comment by ly469097645** [comment]
http://58.23.212.133:5065/tracing-source/file/1632915300250/OLAY广告 夜空中最亮的星.mp3

**Comment by ly469097645** [comment]
http://58.23.212.133:5065/tracing-source/file/1632915309868/Microsoft Edge 2020-09-28 15-48-26.mp4

**Comment by ly469097645** [comment]
这些在浏览器中都能打开，因为带了空格然后播放器就开不了

**Comment by Doikki** [comment]
对中文和空格进行转码Uri.encode(url, "-![.:/,%?&=]")
