### ISSUE TITLE
在线视频播放不了

### ISSUE THREAD

**Issue by jimdaxu** [Doikki/DKVideoPlayer#725]
问题描述：
http://whb.xietuw.com/uploads/video/20211013/a55616f6f2325c90f10a99aa54545cbb.mp4
这个在线视频播放不了

问题机型/系统：
真机 小米Redmi7A Android9 华为mate40 pro 鸿蒙2.0

**Comment by Doikki** [comment]
视频流有问题，建议对视频进行重新编码
