### ISSUE TITLE
添加的多个ControlComponent如何通信？

### ISSUE THREAD

**Issue by NewHuLe** [Doikki/DKVideoPlayer#747]
有这么一个情况，我防抖音做了一个进度拖动的功能，是一个单独的ControlComponent，当我拖动进度的时候，执行onStartTrackingTouch方法时我需要隐藏底层ControlComponent中的点赞，视频描述等等，但是我无法找到更好的方案，除非共用一个ControlComponent，不知道作者有啥好的建议么有？感谢指导。

**Comment by Doikki** [comment]
进度条的control component写一个回调，回调中在调用点赞的ControlComponent，或者像你说的写在一起，我是倾向于写在一起
