### ISSUE TITLE
用mediaplayer解码拖动进度条后进度条会卡住

### ISSUE THREAD

**Issue by cczhr** [Doikki/DKVideoPlayer#775]
![进度条](https://user-images.githubusercontent.com/20502238/177686523-4af50c3e-9333-4e84-b228-35ce80d320b4.gif)
播放的是本地mp4。 如gif显示，用手在屏幕中间修改进度，进度条是能正常显示并且随着播放进度移动的，一旦使用下方的进度条修改进度后，进度条将会卡死。试了用exo解码不会这样。

**Comment by cczhr** [comment]
初步看了下，你的代码当移动进度条的时候 onStartTrackingTouch 走了  mControlWrapper.stopProgress(); 将进度条刷新停了。可是恢复播放的时候 没有向onPlayStateChanged 传 VideoView.STATE_BUFFERED 恢复刷新。

**Comment by Doikki** [comment]
不建议用mediaplayer。问题很多，兼容不过来

**Comment by cczhr** [comment]
> 不建议用mediaplayer。问题很多，兼容不过来
在AndroidMediaPlayer的initPlayer加多个进度移动的监听就可以解决了。

 mMediaPlayer.setOnSeekCompleteListener(new MediaPlayer.OnSeekCompleteListener() {
            @Override
            public void onSeekComplete(MediaPlayer mp) {
                mPlayerEventListener.onInfo(AbstractPlayer.MEDIA_INFO_BUFFERING_END, 0);
            }
        });

**Comment by cczhr** [comment]
mediaplayer 的优势还是有的 播放视频内存占用比较小

**Comment by Doikki** [comment]
嗯，你可以尝试优化优化，有啥好想法可以给我提pr
